export class Demande {
  constructor(
    public id?: number,
    public idSession?: number,
    public idTitreDepense?: number,
    public idtitre?:number,
    public iddirection?: number,
    public motif?: string,
    public fournisseur?: string,
    public devise?:number,
    public montantht?: number,
    public idrubrique?: number,
    public sousrubrique?: string,
    public estregularisation?: boolean,
    public estSupprimer?: boolean,
    public idperiode?: number,
    public comsprescripteur?: string,
    public sousRubrique?: string,
    public depense?: string,
    public etatfinal?: string,
    public typereference?: string,
    public reference?:string,
    public nomReference?: string,
    public typeDevise?: string,
    public validationAchat?: boolean,
    public validationprescripteur?: boolean,
    public validationCdg?: boolean,
    public etatFinal?: boolean,
    public comsCd?: string,
    public estRefuseCdg?:boolean,
    public estRefuseAchat?:boolean,
    public estSoumis?:boolean,
    public identifiant?: string,
    public dateCreation?: string,
    public dateSoumission?: string,

  ) // Autres propriétés de votre modèle de données personnel
  {}
}
